### ISSUE TITLE
Why does OOM Error occur in StatisticsGen in GPU environment?

### ISSUE THREAD

**Issue by jinwooklim** [tensorflow/tfx#1606]
Hi. I am trying TFX in many ways.   
I leave a issue to ask for some confirmation.

### My Environment :
Python: 3.6.10
CUDA: 10.1
CUDNN: 7.6
tensorboard                2.1.1              
tensorflow                 2.1.0              
tensorflow-data-validation 0.21.5             
tensorflow-estimator       2.1.0              
tensorflow-metadata        0.21.1             
tensorflow-model-analysis  0.21.6             
tensorflow-serving-api     2.1.0              
tensorflow-transform       0.21.2  
tfx                        0.21.2 

### Questions:
1. When using Jupyter notebook, there was no problem running MNIST keras example.

2. However, when I run `mnist_pipeline_native.keras.py`,
**StatisticsGen** causes excessive GPU load. And this creates OOM problems

I tried it in an environment where only the CPU was used, but the same problem with Q2. did not occur.

Is there something I'm wrong about?  
If not, is there a bug?

**Comment by charlesccychen** [comment]
Hi @jinwooklim, can you try replacing `--direct_num_workers=0` in the beam arguments with `--direct_num_workers=1`?

**Comment by jinwooklim** [comment]
@charlesccychen  Oh, thank you very much, I solved the problem. Thank you for your time.
